"""cascade delete user relations

Revision ID: 9527bdc616d4
Revises: 
Create Date: 2025-12-31 00:03:15.724970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9527bdc616d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doua', schema=None) as batch_op:
        batch_op.alter_column('name_latin',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('favorite_adhkar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorite_adhkar_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'adhkar', ['adhkar_id'], ['id'])

    with op.batch_alter_table('favorite_doua', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorite_doua_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'doua', ['doua_id'], ['id'])

    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorite_recipe_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('khatma', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('khatma_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_constraint(batch_op.f('recipes_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_adhkar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_adhkar_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_adhkar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_adhkar_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipes_ibfk_1'), 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('khatma', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('khatma_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_recipe_ibfk_2'), 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite_doua', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_doua_ibfk_2'), 'doua', ['doua_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite_adhkar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_adhkar_ibfk_2'), 'adhkar', ['adhkar_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('doua', schema=None) as batch_op:
        batch_op.alter_column('name_latin',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
